db.regex.insertMany([
        {
            comunidad: "Andalucia", 
            ciudad: "Sevilla",
            pueblo: "Dos hermanas",
            habitantes: "130.000",
            gentilicio: "nazareno",
            Monumento_hitorico: "Alqueria del Pilar",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Cadiz",
            pueblo: "Seteneil de las bodegas",
            habitantes: "2.769",
            gentilicio: "setenileño",
            Monumento_hitorico: "Fortaleza Nazari",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Malaga",
            pueblo: "Ronda",
            habitantes: "34.000",
            gentilicio: "rondeño",
            Monumento_hitorico: "Punte del Tajo",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Cadiz",
            pueblo: "Olvera",
            habitantes: "8.124",
            gentilicio: "olvereño",
            Monumento_hitorico: "Castillo de Olvera",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Cadiz",
            pueblo: "Tarifa",
            habitantes: "18.169",
            gentilicio: "tarifeño",
            Monumento_hitorico: "Ruinas romanas de Baelo Claudia",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Cadiz",
            pueblo: "Zahara de la sierra",
            habitantes: "1.400",
            gentilicio: "zahareño",
            Monumento_hitorico: "Iglesia mayor",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Sevilla",
            pueblo: "Utrera",
            habitantes: "52.617",
            gentilicio: "utrerano",
            Monumento_hitorico: "Iglesia Santa Maria de la Mesa",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Sevilla",
            pueblo: "Los Palacios",
            habitantes: "38.246",
            gentilicio: "palaciegos",
            Monumento_hitorico: "Parroquia Mayor",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Sevilla",
            pueblo: "Moron de la Frontera",
            habitantes: "27.844",
            gentilicio: "moronero",
            Monumento_hitorico: "Castillo arabe",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Sevilla",
            pueblo: "Carmona",
            habitantes: "28.620",
            gentilicio: "carmonense",
            Monumento_hitorico: "Necropolis romana",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Cadiz",
            pueblo: "Conil de la frontera",
            habitantes: "22.427",
            gentilicio: "cooleño",
            Monumento_hitorico: "Iglesia de Santa Catalina",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Cadiz",
            pueblo: "Vejer de la frontera",
            habitantes: "12.739",
            gentilicio: "vejeriego",
            Monumento_hitorico: "Torre del Mayorazgo",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Malaga",
            pueblo: "Marbella",
            habitantes: "141.463",
            gentilicio: "marbelli",
            Monumento_hitorico: "Villa Romana",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Cordoba",
            pueblo: "Priego de Cordoba",
            habitantes: "22.285",
            gentilicio: "prieguense",
            Monumento_hitorico: "Iglesia de la Aurora",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Cordoba",
            pueblo: "Iznajar",
            habitantes: "4.343",
            gentilicio: "iznajeño",
            Monumento_hitorico: "Castillo de Iznajar",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Granada",
            pueblo: "Montefrio",
            habitantes: "5.479",
            gentilicio: "montefrieño",
            Monumento_hitorico: "El pateon y viejo cementerio",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Granada",
            pueblo: "Salobreña",
            habitantes: "12.396",
            gentilicio: "salobreño",
            Monumento_hitorico: "El castillo de Salobreña",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Jaen",
            pueblo: "Andujar",
            habitantes: "37.113",
            gentilicio: "andujareño",
            Monumento_hitorico: "Basilica de Nuestra Señora de las Cabeza",
        },
        {
            comunidad: "Andalucia", 
            ciudad: "Jaen",
            pueblo: "Baeza",
            habitantes: "15.902",
            gentilicio: "baezano",
            Monumento_hitorico: "La plaza de Santa Maria",
        }
    ]);